export const FETCH_METRICS_START = "FETCH_METRICS_START"
export const FETCH_METRICS_SUCCESS = "FETCH_METRICS_SUCCESS"
export const FETCH_METRICS_FAILED = "FETCH_METRICS_FAILED"

export const FETCH_TIME_SERIES_START = "FETCH_TIME_SERIES_START"
export const FETCH_TIME_SERIES_SUCCESS = "FETCH_TIME_SERIES_SUCCESS"
export const FETCH_TIME_SERIES_FAILED = "FETCH_TIME_SERIES_FAILED"